### ISSUE TITLE
Language code in language.rb is not in sync with the codes in the java code in TestBase.java

### ISSUE THREAD

**Issue by jonhamidi** [Traap/amber#62] opened 2018-03-27 18:36 UTC
language.rb:
     Code  = {"zz" => "n/a", "da" => "Dansk", "de" => "Deutsch", "en"=> "English",
            "es" => "Espanol", "fr-ca" => "CA French - Canadian",
            "fr-eu" => "EU French - European", "ge" => "German",
            "it" => "Italiano", "ne" => "Nederlands", "no" => "Norsk",
            "sv" => "Svenska"}

TestBase.java:
	switch (testLanguage) {

		case "en":
			testLanguage = "English";
			break;
		case "fr-eu":
			testLanguage = "French - European (new Jan 2016)";
			break;
		case "fr-ca":
			testLanguage = "French - Canadian";
			break;
		case "ge":
			testLanguage = "Deutsch";
			break;
		case "es":
			testLanguage = "Español";
			break;
		case "it":
			testLanguage = "Italiano";
			break;
		case "ne":
			testLanguage = "Nederlands";
			break;
		case "no":
			testLanguage = "Norsk";
			break;
		case "sv":
			testLanguage = "Svenska";
			break;
		case "da":
			testLanguage = "Dansk";
			break;

		}

**Comment by sqlkamal** [comment] 2018-03-27 19:51
@Traap We have similar ticket in Centerium now. I will make changes to Recent_Excel branch.

**Comment by Traap** [comment] 2018-03-28 14:31
"ge" => "german" is a duplicate of "de" => "Deutsch"

**Closed** 2018-03-28 14:45 UTC
Labels: bug
